version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: MarketDB
    ports:
      - "7474:7474"   
      - "7687:7687"   
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    volumes:
      - neo4j_data:/data       
      - neo4j_logs:/logs       
      
      
volumes:
  neo4j_data:
  neo4j_logs:
 